# Generated by Django 6.0.1 on 2026-01-07 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_completed', models.IntegerField(default=0, verbose_name='Q1 complétées')),
                ('q2_completed', models.IntegerField(default=0, verbose_name='Q2 complétées')),
                ('q3_completed', models.IntegerField(default=0, verbose_name='Q3 complétées')),
                ('q4_completed', models.IntegerField(default=0, verbose_name='Q4 complétées')),
                ('total_tasks_created', models.IntegerField(default=0, verbose_name='Total créées')),
                ('total_tasks_completed', models.IntegerField(default=0, verbose_name='Total complétées')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('due_date', models.DateTimeField(help_text='Date limite pour accomplir cette tâche', verbose_name="Date d'échéance")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('urgency_score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='1 = Pas urgent, 5 = Très urgent', verbose_name="Niveau d'urgence")),
                ('importance_score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='1 = Pas important, 5 = Très important', verbose_name="Niveau d'importance")),
                ('status', models.CharField(choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Terminé')], default='TODO', max_length=20, verbose_name='Statut')),
                ('quadrant', models.CharField(choices=[('Q1', 'Urgent & Important - À FAIRE MAINTENANT'), ('Q2', 'Important mais pas urgent - À PLANIFIER'), ('Q3', 'Urgent mais pas important - À DÉLÉGUER'), ('Q4', 'Ni urgent ni important - À ÉLIMINER')], default='Q2', editable=False, max_length=2, verbose_name='Quadrant')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['-importance_score', '-urgency_score', 'due_date'],
                'indexes': [models.Index(fields=['user', 'quadrant', 'status'], name='tasks_task_user_id_8b7b4d_idx'), models.Index(fields=['due_date'], name='tasks_task_due_dat_bce847_idx')],
            },
        ),
    ]
